language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  include:
    - php: 5.5
      env: COVERAGE=yes
    - php: 5.6
      env: COVERAGE=yes
    - php: 7
      env: COVERAGE=yes
install:
- composer install --no-plugins
script:
  - >
    if [[ "$COVERAGE" == "yes" ]]; then
      ./vendor/bin/phpunit --coverage-clover=coverage.clover
    else
      ./vendor/bin/phpunit
    fi

after_script:
  - >
    if [[ "$COVERAGE" == "yes" ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --access-token=$SCRUTINIZER_TOKEN --format=php-clover coverage.clover
    fi
env:
  global:
    secure: VhT/7j2OTOv7ttyjzs6/8p7bRtkM0ZSs1rn/8rI0spQqqyZDZN64f2x7Q4gxZR4nC3rzSDhZiVjw5fhEu+tZmFaDS8f8Il9dEomUqKAZmh1AlBr1/IQQXbUa+jMJTPxGQJ9MGVkFDz5qHnQR2iMih3yVMJiFxfF7zyvVlsO4tfw0n0Un7sauNjMmgOsgqRLkt9waZIoYOJKv5MI1LYDohssaKpNrlx/XcRhNtx5h1VnN3/jRbLe/bYapObjM4qFWWSGZzCQ6AIH4TCgqRz5/teCweaOkoKIoBGjvcaS0UwnAoSOz+gQ6dlmiSkSvh1EWWE3ArjSdxvt8i2TK50rDYqksI+2/NOU4jtVoX4PdTHbjcpAjOjbnb/iJgCWVNfMua5AhwNNrRd/Qp0hFKhnxzSnGPvbEsHU72ug4Xpy+Qlt+VgQe16VnxFJuD0iLW6gyMoEAay34/SuMAr9NdRiaKeaZqs+rg4hM1gKbJXkBHIORFrDELxNSEnCi5jWV5n9QhonKkJRGyO1ismuOMi4lxgEuaKqftLmZCT27JDg2PCVzNM3QUmylnSu2A3HMCj/iYK2VnPSEkaV9Ppq069/JlQtiyPCl8zN8+0PWxj/fDWb/cv7zx6rw2RKtxdS2qvsULABvusd2EMNZjBUJW44aVMjt5y/yusAeGwRQvAf4uHA=
